name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Esto asegura que solo cuando hagas un push a la rama main se ejecutará el deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          # Si estás utilizando un generador de sitio estático, como React, agrega los comandos aquí
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Cambia esto por la carpeta donde estén los archivos estáticos
