name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # El workflow se ejecutará solo cuando se haga un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config --global user.name 'your-github-username'
        git config --global user.email 'your-email@example.com'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
